.\" @(#)psfstriptable.1
.TH PSFSTRIPTABLE 1 "25 Oct 1994"
.SH NAME
psfstriptable \- remove the embedded Unicode character table from a console font
.SH SYNOPSIS
.B psfstriptable
.I fontfile
.RI [ outfile ]
.SH DESCRIPTION
.IX "psfstriptable command" "" "\fLpsfstriptable\fR command"  
.LP
.B psfstriptable
reads a .psf format console font from 
.IR fontfile ,
or standard input if
.I fontfile
is a single dash (\-), which may have
an embedded Unicode font table, and writes (to standard output or the
specified file) a .psf format console font file without an embedded
character table.
.SH "SEE ALSO"
.BR setfont (8),
.BR psfaddtable (1),
.BR psfgettable (1)


