#!/bin/sh
#
# From klaus.stehle@uni-tuebingen.de Tue Jan 25 07:24:02 2000
#
# A small shell script version of the `showconsolefont' C program
#

echo -e "\033%G"
for L in "0 2 4 6" "1 3 5 7"; do
    for P in 0 1 2 3 4 5 6 7; do
	for U in 0 1 2 3; do
	    for K in $L; do
		echo -ne "  \357\20$U\2$K$P"
	    done
	done
	echo
    done
    echo
done
echo -ne "\033%@"
