struct syn const synonyms[] = {
	{ "Control_h", "BackSpace" },
	{ "Control_i", "Tab" },
	{ "Control_j", "Linefeed" },
	{ "Home", "Find" },
	/* Unfortunately Delete already denotes ASCII 0177 */
	/* { "Delete", "Remove" }, */
	{ "End", "Select" },
	{ "PageUp", "Prior" },
	{ "PageDown", "Next" },
	{ "F246", "Backtab" },
	{ "multiplication", "multiply" },
	{ "pound", "sterling" },
	{ "pilcrow", "paragraph" },
	{ "Oslash", "Ooblique" },
	{ "Shift_L", "ShiftL" },
	{ "Shift_R", "ShiftR" },
	{ "Control_L", "CtrlL" },
	{ "Control_R", "CtrlR" },
	{ "AltL", "Alt" },
	{ "AltR", "AltGr" },
	{ "Alt_L", "Alt" },
	{ "Alt_R", "AltGr" },
	{ "AltGr_L", "Alt" },
	{ "AltGr_R", "AltGr" },
	{ "AltLLock", "Alt_Lock" },
	{ "AltRLock", "AltGr_Lock" },
	{ "SCtrl", "SControl" },
	{ "Spawn_Console", "KeyboardSignal" },
	{ "Uncaps_Shift", "CapsShift" },
	/* the names of the Greek letters are spelled differently
   in the iso-8859-7 and the Unicode standards */
	{ "Greek_ALPHA", "Alpha" },
	{ "Greek_ALPHAaccent", "Alphaaccent" },
	{ "Greek_BETA", "Beta" },
	{ "Greek_CHI", "Khi" },
	{ "Greek_DELTA", "Delta" },
	{ "Greek_EPSILON", "Epsilon" },
	{ "Greek_EPSILONaccent", "Epsilonaccent" },
	{ "Greek_ETA", "Eta" },
	{ "Greek_ETAaccent", "Etaaccent" },
	{ "Greek_GAMMA", "Gamma" },
	{ "Greek_IOTA", "Iota" },
	{ "Greek_IOTAaccent", "Iotaaccent" },
	{ "Greek_KAPPA", "Kappa" },
	{ "Greek_LAMBDA", "Lamda" },
	{ "Greek_LAMDA", "Lamda" },
	{ "Greek_MU", "Mu" },
	{ "Greek_NU", "Nu" },
	{ "Greek_OMEGA", "Omega" },
	{ "Greek_OMEGAaccent", "Omegaaccent" },
	{ "Greek_OMICRON", "Omicron" },
	{ "Greek_OMICRONaccent", "Omicronaccent" },
	{ "Greek_PHI", "Phi" },
	{ "Greek_PI", "Pi" },
	{ "Greek_PSI", "Psi" },
	{ "Greek_RHO", "Rho" },
	{ "Greek_SIGMA", "Sigma" },
	{ "Greek_TAU", "Tau" },
	{ "Greek_THETA", "Theta" },
	{ "Greek_UPSILON", "Upsilon" },
	{ "Greek_UPSILONaccent", "Upsilonaccent" },
	{ "Greek_UPSILONdieresis", "Upsilondieresis" },
	{ "Greek_XI", "Ksi" },
	{ "Greek_ZETA", "Zeta" },
	{ "Greek_alpha", "alpha" },
	{ "Greek_alphaaccent", "alphaaccent" },
	{ "Greek_beta", "beta" },
	{ "Greek_accentdieresis", "diaeresisaccent" },
	{ "Greek_chi", "khi" },
	{ "Greek_delta", "delta" },
	{ "Greek_epsilon", "epsilon" },
	{ "Greek_epsilonaccent", "epsilonaccent" },
	{ "Greek_eta", "eta" },
	{ "Greek_etaaccent", "etaaccent" },
	{ "Greek_gamma", "gamma" },
	{ "Greek_horizbar", "horizontal_bar" },
	{ "Greek_iota", "iota" },
	{ "Greek_iotaaccent", "iotaaccent" },
	{ "Greek_iotaaccentdieresis", "iotadiaeresisaccent" },
	{ "Greek_iotadieresis", "iotadiaeresis" },
	{ "Greek_kappa", "kappa" },
	{ "Greek_lambda", "lamda" },
	{ "Greek_lamda", "lamda" },
	{ "Greek_mu", "mu" },
	{ "Greek_nu", "nu" },
	{ "Greek_omega", "omega" },
	{ "Greek_omegaaccent", "omegaaccent" },
	{ "Greek_omicron", "omicron" },
	{ "Greek_omicronaccent", "omicronaccent" },
	{ "Greek_phi", "phi" },
	{ "Greek_pi", "pi" },
	{ "Greek_psi", "psi" },
	{ "Greek_rho", "rho" },
	{ "Greek_sigma", "sigma" },
	{ "Greek_tau", "tau" },
	{ "Greek_theta", "theta" },
	{ "Greek_upsilon", "upsilon" },
	{ "Greek_upsilonaccent", "upsilonaccent" },
	{ "Greek_upsilonaccentdieresis", "upsilondiaeresisaccent" },
	{ "Greek_upsilondieresis", "upsilondieresis" },
	{ "Greek_xi", "ksi" },
	{ "Greek_zeta", "zeta" },
	{ "lambda", "lamda" },
	{ "Lambda", "Lamda" },
	{ "xi", "ksi" },
	{ "Xi", "Ksi" },
	{ "chi", "khi" },
	{ "Chi", "Khi" },
	/* diacriticals */
	{ "tilde", "asciitilde" },
	{ "circumflex", "asciicircum" },
	/* dead_ogonek, dead_caron, dead_breve and dead_doubleacute didn't exist in
	 * the kernel, so they were introduced as aliases for other dead keys. For
	 * backward compatilibty they remain as aliases and the real names are
	 * prefixed with dead_k (kernel).
	 */
	{ "dead_ogonek", "dead_cedilla" },
	{ "dead_caron", "dead_circumflex" },
	{ "dead_breve", "dead_tilde" },
	{ "dead_doubleacute", "dead_tilde" },
	/* turkish */
	{ "Idotabove", "Iabovedot" },
	{ "dotlessi", "idotless" },
	/* cyrillic */
	{ "no-break_space", "nobreakspace" },
	{ "paragraph_sign", "section" },
	{ "soft_hyphen", "hyphen" },
	{ "bielorussian_cyrillic_capital_letter_i", "ukrainian_cyrillic_capital_letter_i" },
	{ "cyrillic_capital_letter_kha", "cyrillic_capital_letter_ha" },
	{ "cyrillic_capital_letter_ge", "cyrillic_capital_letter_ghe" },
	{ "cyrillic_capital_letter_ia", "cyrillic_capital_letter_ya" },
	{ "cyrillic_capital_letter_iu", "cyrillic_capital_letter_yu" },
	{ "cyrillic_capital_letter_yeri", "cyrillic_capital_letter_yeru" },
	{ "cyrillic_capital_letter_reversed_e", "cyrillic_capital_letter_e" },
	{ "cyrillic_capital_letter_ii", "cyrillic_capital_letter_i" },
	{ "cyrillic_capital_letter_short_ii", "cyrillic_capital_letter_short_i" },
	{ "bielorussian_cyrillic_small_letter_i", "ukrainian_cyrillic_small_letter_i" },
	{ "cyrillic_small_letter_kha", "cyrillic_small_letter_ha" },
	{ "cyrillic_small_letter_ge", "cyrillic_small_letter_ghe" },
	{ "cyrillic_small_letter_ia", "cyrillic_small_letter_ya" },
	{ "cyrillic_small_letter_iu", "cyrillic_small_letter_yu" },
	{ "cyrillic_small_letter_yeri", "cyrillic_small_letter_yeru" },
	{ "cyrillic_small_letter_reversed_e", "cyrillic_small_letter_e" },
	{ "cyrillic_small_letter_ii", "cyrillic_small_letter_i" },
	{ "cyrillic_small_letter_short_ii", "cyrillic_small_letter_short_i" },
	{ "ukrainian_cyrillic_small_letter_ghe_with_upturn", "cyrillic_small_letter_ghe_with_upturn" },
	{ "ukrainian_cyrillic_capital_letter_ghe_with_upturn", "cyrillic_capital_letter_ghe_with_upturn" },
	/* iso-8859-7 */
	{ "rightanglequote", "guillemotright" }
};
