#!/bin/sh

NEED_UNICODE=
for f in "$HOME/.i18n" /etc/sysconfig/i18n; do
	if [ -s "$f" ] && . "$f" ; then
		break
	fi
done

case "$LANG" in 
	*.utf8|*.UTF-8) NEED_UNICODE=1 ;;
esac

if [ "$TERM" = 'linux' -a "`/sbin/consoletype`" = 'vt' ]; then
	[ -n "$NEED_UNICODE" ] &&
		f='/bin/unicode_start' ||
		f='/bin/unicode_stop'

	[ ! -x "$f" ] ||
		"$f"
fi
