#!/bin/sh
#
#

> .null

for x in ../*/*.c ../*/*/*.c; do
echo "$x \\"
done > POTFILES
echo .null   >> POTFILES

cd ..
for x in */*.c */*/*.c; do
echo "$x"
done > po/POTFILES.in
cd po

for x in POTFILES POTFILES.in; do
sort -uo "$x" "$x"
done
