.\" @(#)chvt.1 1.0 970126 aeb
.TH CHVT 1 "24 October 2024" "kbd"
.SH NAME
chvt \- change foreground virtual terminal
.SH SYNOPSIS
.B chvt
[\fI\,option\/\fR...]
[\fI\,N\/\fR]
.SH DESCRIPTION
The command
.B chvt
.I N
makes
.I /dev/ttyN
the foreground terminal.
(The corresponding screen is created if it did not exist yet.
To get rid of unused VTs,
use
.BR deallocvt (1).)
The key combination
.RI (Ctrl-)LeftAlt-F N
(with
.I N
in the range 1-12) usually has a similar effect.
.SH OPTIONS
.TP
\fB\-C\fR, \fB\-\-console\fR=\fI\,DEV\/\fR
the console device to be used.
.TP
\fB\-V\fR, \fB\-\-version\fR
print version number.
.TP
\fB\-h\fR, \fB\-\-help\fR
print this usage message.
.SH AUTHORS
Andries Brouwer <aeb@cwi.nl>
.SH "SEE ALSO"
.BR deallocvt (1),
.BR openvt (1)
