.TH FGCONSOLE 1 "24 October 2024" "kbd"

.SH NAME
fgconsole \- print the number of the active VT.

.SH SYNOPSIS
.B fgconsole
[\fI\,options\/\fR]
.SH DESCRIPTION
If the active Virtual Terminal is
.IR /dev/ttyN ,
then prints
.I N
on standard output.

If the console is a serial console, then
"serial"
is printed instead.

.SH OPTIONS
.TP
\fB\-n\fR, \fB\-\-next\-available\fR
Will show the next unallocated virtual terminal. Normally 6 virtual
terminals are allocated, with number 7 used for X; this will return
"8" in this case.
.TP
\fB\-C\fR, \fB\-\-console\fR=\fI\,DEV\/\fR
the console device to be used.
.TP
\fB\-V\fR, \fB\-\-version\fR
print version number.
.TP
\fB\-h\fR, \fB\-\-help\fR
print this usage message.

.SH NOTES
Under
.IR devfs ,
the consoles are in
.IR /dev/vc/N .
.I devfsd
may maintain symlinks for compatibility.
.SH AUTHORS
Andries Brouwer <aeb@cwi.nl>
.br
Manpage by Alastair McKinstry <mckinstry@computer.org>
.SH "SEE ALSO"
.BR chvt (1),
.BR deallocvt (1),
.BR openvt (1)
