.\" @(#)man/man8/getkeycodes.8	1.0 Nov  8 22:30:48 MET 1994
.TH GETKEYCODES 8 "8 Nov 1994" "kbd"
.SH NAME
getkeycodes \- print kernel scancode-to-keycode mapping table
.SH SYNOPSIS
.B getkeycodes
[\fI\,options\/\fR]
.SH DESCRIPTION
The
.I getkeycodes
command prints the kernel scancode-to-keycode mapping table.
.SH OPTIONS
.TP
\fB\-V\fR, \fB\-\-version\fR
print version number;
.TP
\fB\-h\fR, \fB\-\-help\fR
print this usage message.
.SH "SEE ALSO"
.BR setkeycodes (8)


