.\" @(#)man/man8/setvtrgb.8	1.0 Mar  3 12:32:18 CST 2011
.TH SETVTRGB 8 "3 Mar 2011" "kbd"
.SH NAME
setvtrgb \- set the virtual terminal RGB colors
.SH SYNOPSIS
.B setvtrgb
[\fI\,options\/\fR]
.I vga|FILE|\-
.SH DESCRIPTION
The
.I setvtrgb
command takes a single argument, either the string
.B vga
, or a path to a file containing the colors to be used by
the Linux virtual terminals.

You can choose to write the colors in decimal or hexadecimal format,
it will be detected on runtime.

Decimal
.B FILE
format should be exactly 3 lines of 16
comma-separated decimal values for RED, GREEN, and BLUE.

To seed a valid
.B FILE
:
.RS
.B "cat /sys/module/vt/parameters/default_{red,grn,blu} > FILE"
.RE

And then edit the values in
.B FILE

Hexadecimal
.B FILE
format should be exactly 16 lines of hex triplets for RED, GREEN and BLUE,
prefixed with a number sign (#). For example:
.nf
.RS
.B #000000
.B #AA0000
.B #00AA00
.B #AA5500
.B #0000AA
.B #AA00AA
.B #00AAAA
.B #AAAAAA
.B #555555
.B #FF5555
.B #55FF55
.B #FFFF55
.B #5555FF
.B #FF55FF
.B #55FFFF
.B #FFFFFF
.RE
.fi

.SH OPTIONS
.TP
\fB\-C\fR, \fB\-\-console\fR=\fI\,DEV\/\fR
the console device to be used;
.TP
\fB\-h\fR, \fB\-\-help\fR
Prints usage message and exits.
.TP
\fB\-V\fR, \fB\-\-version\fR
Prints version number and exists.

.SH AUTHOR
The utility is written by Alexey Gladkov, Seth Forshee, Dustin Kirkland.

.SH DOCUMENTATION
Documentation by Dustin Kirkland.
