.\" @(#)man/man8/setvtrgb.8	1.0 Mar  3 12:32:18 CST 2011
.TH SETVTRGB 8 "3 Mar 2011" "kbd"
.SH NAME
setvtrgb \- set the virtual terminal RGB colors
.SH SYNOPSIS
.B setvtrgb
[\fI\,options\/\fR]
.I vga|FILE|\-
.SH DESCRIPTION
The
.I setvtrgb
command takes a single argument, either the string
.B vga
, or a path to a file
containing the red, green, and blue colors to be used by the Linux virtual terminals.

If you use the
.B FILE
parameter,
.B FILE
should be exactly 3 lines of 16
comma-separated decimal values for RED, GREEN, and BLUE.

To seed a valid
.B FILE
:
.RS
.B "cat /sys/module/vt/parameters/default_{red,grn,blu} > FILE"
.RE

And then edit the values in
.B FILE

.SH OPTIONS
.TP
\fB\-C\fR, \fB\-\-console\fR=\fI\,DEV\/\fR
the console device to be used;
.TP
\fB\-h\fR, \fB\-\-help\fR
Prints usage message and exits.
.TP
\fB\-V\fR, \fB\-\-version\fR
Prints version number and exists.

.SH AUTHOR
The utility is written by Alexey Gladkov, Seth Forshee, Dustin Kirkland.

.SH DOCUMENTATION
Documentation by Dustin Kirkland.
