
#line 3 "loadkeys.analyze.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#ifdef __GNUC__
static void yy_fatal_error (yyconst char msg[]  ) __attribute__((noreturn));
#else
static void yy_fatal_error (yyconst char msg[]  );
#endif

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 48
#define YY_END_OF_BUFFER 49
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[504] =
    {   0,
        0,    0,    0,    0,   45,   45,    0,    0,   49,   47,
        6,    5,   47,   40,   47,   16,   15,   14,   12,   12,
        8,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   45,   46,   48,    3,   48,    6,    0,    7,    0,
        0,   12,    0,   12,    0,   33,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   35,
        0,    0,    0,    0,    0,    0,   10,    0,    0,    0,

        4,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   10,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   45,   42,   41,   43,   44,    0,    3,
       39,    0,   39,    0,   12,   23,    0,   23,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   36,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       23,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   41,    2,
       38,   37,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,

       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   41,   37,    0,    0,
       24,    0,    0,    0,    0,   27,   28,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   20,
       21,    0,   21,    0,    0,   34,    0,    0,    0,    0,
        0,    0,    0,   21,    0,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   25,   26,    9,
        9,   11,    0,    0,    0,    0,    0,    0,    0,    9,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,    9,
        9,   13,   13,   13,   13,   13,   13,   13,    9,    0,
        0,   17,   32,   22,    0,    0,   19,   18,   31,    0,
        1,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,    1,    0,    0,    0,    0,    0,    1,   13,
       13,   13,   13,   13,    0,   29,   13,   13,    0,   13,

       30,   13,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    1,    1,    7,    1,
        1,    1,    8,    9,   10,    1,    1,   11,   12,   12,
       12,   12,   12,   12,   12,   13,   13,    1,    1,    1,
       14,    1,    1,    1,   15,   16,   17,   18,   19,   20,
       21,   22,   23,   24,   25,   26,   27,   28,   29,   30,
       24,   31,   32,   33,   34,   24,   24,   35,   36,   24,
        1,   37,    1,    1,   38,    1,   39,   16,   40,   41,

       42,   43,   44,   45,   46,   24,   47,   48,   49,   50,
       51,   52,   24,   53,   54,   55,   56,   24,   24,   35,
       57,   24,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[58] =
    {   0,
        1,    1,    2,    1,    3,    1,    1,    1,    1,    1,
        4,    4,    4,    1,    4,    4,    4,    4,    4,    4,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    3,    5,    4,    4,
        4,    4,    4,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5
    } ;

static yyconst flex_int16_t yy_base[517] =
    {   0,
        0,    0,   57,    0,  110,  111,  721,  720,  724,  727,
      721,  727,  719,  727,  684,  727,  727,  727,  106,  108,
      727,   96,  110,   94,  110,   96,  105,  118,  105,  122,
      717,  110,  123,  668,  668,  675,  666,  667,   82,  663,
      659,  134,    0,  157,  106,  150,  131,  141,  158,  142,
      162,  151,  156,  661,  661,  668,  659,  660,  130,  656,
      652,    0,  727,  209,  727,  195,  703,  701,  727,  696,
      211,  172,    0,  213,  154,  727,  164,  672,  686,  200,
      669,  647,  659,  180,  644,  665,  642,  658,  636,  727,
      677,  652,  667,  658,  642,  634,  727,    0,  652,  629,

      727,  177,  182,  632,  644,  184,  629,  628,  640,  622,
      639,  631,  623,  619,    0,  184,    0,  198,  644,  658,
      208,  641,  619,  631,  191,  616,  637,  614,  630,  608,
        0,  649,  624,  639,  630,  614,  606,    0,  624,  601,
      205,  209,  604,  616,  194,  601,  600,  612,  594,  611,
      603,  595,  591,    0,  727,  236,  727,  727,  201,  727,
      727,  639,  638,  238,    0,  241,  242,  244,  612,  612,
      612,  608,  614,  585,  585,  585,  581,  587,  727,  239,
      241,  611,  587,  612,  608,  587,  583,    0,  613,  588,
      245,  572,  572,  572,  568,  574,  573,   93,  574,  576,

      572,  578,  253,  247,  257,  584,  584,  584,  580,  586,
      557,  557,  557,  553,  559,    0,  244,  259,  583,  559,
      584,  580,  559,  555,  585,  560,  259,  544,  544,  544,
      540,  546,  545,  235,  546,  548,  544,  550,  261,  727,
      727,  727,  293,  247,  557,  534,  533,  553,  552,  554,
      551,  261,  262,  264,  530,  527,  276,  550,  563,  526,
      537,  524,  535,  545,  522,  538,  542,  514,  518,    0,
      541,  518,  512,  510,  509,  511,  508,  258,  504,  508,
      519,  507,  501,  505,  506,  522,  275,  499,  498,  518,
      517,  519,  516,  283,  278,  280,  495,  492,  289,  515,

      528,  491,  502,  489,  500,  510,  487,  503,  507,  479,
      483,  506,  483,  477,  475,  474,  476,  473,  269,  469,
      473,  484,  472,  466,  470,  471,  727,  727,  511,  281,
      727,  495,  497,  483,  485,  727,  727,  468,  467,  469,
      468,  455,  457,  489,  476,  464,  452,  462,  450,  727,
      293,  480,  297,  456,    0,  727,  454,  456,  443,  445,
      454,  453,  441,  277,  448,    0,  294,  469,  471,  457,
      459,    0,    0,  442,  441,  443,  442,  429,  431,  463,
      450,  438,  426,  436,  424,    0,  305,  454,  307,  430,
        0,  428,  430,  417,  419,  428,  427,  415,  289,  422,

      317,  442,  431,  444,  436,  415,  414,  404,  403,  415,
      408,  436,  422,  411,  398,  409,  396,  727,  727,  417,
      394,  727,  401,  391,  403,  396,  401,  400,  387,  386,
      319,  416,  405,  418,  410,  389,  388,  378,  377,  389,
      382,  410,  396,  385,  372,  383,  370,    0,    0,  391,
      368,  375,  365,  377,  370,  375,  374,  361,  360,  312,
      393,  727,  727,  727,  369,  368,  727,  727,  727,  364,
      396,  313,  370,    0,    0,    0,  329,  327,    0,    0,
        0,  326,  363,  322,  330,  305,  304,  303,  354,  324,
      321,  298,  297,  296,  312,  727,  313,    0,  332,  334,

      727,    0,  727,  373,  378,  383,  388,  390,  395,  400,
      405,  346,  340,  273,  134,  122
    } ;

static yyconst flex_int16_t yy_def[517] =
    {   0,
      503,    1,  503,    3,  504,  504,  505,  505,  503,  503,
      503,  503,  506,  503,  507,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  508,  508,  508,  508,  508,  508,  508,  508,  508,
      508,  508,  508,  508,  508,  508,  508,  508,  508,  508,
      508,  509,  503,  503,  503,  510,  503,  506,  503,  503,
      511,  503,  512,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  513,  503,  503,

      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  508,  508,  508,  508,  508,  508,
      508,  508,  508,  508,  508,  508,  508,  508,  508,  508,
      508,  508,  508,  508,  508,  508,  508,  508,  508,  508,
      508,  508,  508,  508,  508,  508,  508,  508,  508,  508,
      508,  508,  508,  509,  503,  503,  503,  503,  510,  503,
      503,  503,  503,  503,  512,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  514,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,

      503,  503,  508,  508,  508,  508,  508,  508,  508,  508,
      508,  508,  508,  508,  508,  508,  508,  508,  508,  508,
      508,  508,  508,  508,  508,  508,  508,  508,  508,  508,
      508,  508,  508,  508,  508,  508,  508,  508,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  515,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  508,  508,  508,  508,  508,
      508,  508,  508,  508,  508,  508,  508,  508,  508,  508,

      508,  508,  508,  508,  508,  508,  508,  508,  508,  508,
      508,  508,  508,  508,  508,  508,  508,  508,  508,  508,
      508,  508,  508,  508,  508,  508,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  516,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  508,  508,  508,  508,  508,
      508,  508,  508,  508,  508,  508,  508,  508,  508,  508,
      508,  508,  508,  508,  508,  508,  508,  508,  508,  508,
      508,  508,  508,  508,  508,  508,  508,  508,  508,  508,

      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      508,  508,  508,  508,  508,  508,  508,  508,  508,  508,
      508,  508,  508,  508,  508,  508,  508,  508,  508,  508,
      508,  508,  508,  508,  508,  508,  508,  508,  508,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  508,  508,  508,  508,  508,  508,  508,  508,  508,
      508,  508,  508,  503,  503,  503,  503,  503,  503,  508,
      508,  508,  508,  508,  503,  503,  508,  508,  503,  508,

      503,  508,    0,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503
    } ;

static yyconst flex_int16_t yy_nxt[785] =
    {   0,
       10,   11,   12,   13,   14,   13,   15,   16,   17,   18,
       19,   20,   20,   21,   22,   10,   23,   10,   10,   24,
       10,   10,   10,   10,   25,   10,   10,   10,   26,   27,
       10,   28,   29,   30,   10,   10,   31,   10,   32,   33,
       10,   10,   34,   10,   10,   35,   36,   10,   10,   10,
       37,   38,   10,   39,   40,   41,   10,   10,   11,   12,
       13,   14,   13,   15,   16,   17,   18,   19,   20,   20,
       21,   42,   43,   44,   43,   43,   45,   43,   43,   43,
       43,   46,   43,   43,   43,   47,   48,   43,   49,   50,
       51,   43,   43,   31,   10,   52,   53,   43,   43,   54,

       43,   43,   55,   56,   43,   43,   43,   57,   58,   43,
       59,   60,   61,   43,   63,   63,   72,   72,   74,   74,
       74,   75,   86,   90,   78,  422,  112,   76,   88,   98,
       91,   79,  280,   97,  127,  102,  113,  355,   80,   93,
       73,  281,   81,   77,   87,   90,   64,   64,   82,   76,
       94,   89,   92,   99,   83,   97,  128,  103,  131,  116,
       84,  104,   95,   76,   85,  117,  132,  105,  129,   98,
      138,  119,   96,  106,  151,  100,  141,  107,  120,  134,
      131,  118,   72,   72,  152,  121,  166,  117,  133,  122,
      135,  130,  138,  139,  143,  123,  167,  160,  142,  160,

      144,  124,  136,  160,  117,  240,  145,  125,  167,  167,
      146,  126,  137,  155,  167,  140,  203,  163,  168,  156,
      156,  164,  164,   74,   74,   74,  171,  172,  176,  177,
      204,  167,  194,  195,  208,  209,  191,  204,  204,  213,
      214,  204,  230,  231,  242,  157,  239,  239,  243,  243,
      244,  244,  205,  244,  244,  258,  244,  260,  158,  204,
      300,  245,  244,  227,  246,  259,  244,  261,  244,  330,
      301,  327,  327,  286,  321,  302,  270,  288,  244,  244,
      262,  244,  244,  322,  287,  303,  336,  247,  273,  263,
      287,  337,  330,  338,  287,  340,  287,  367,  304,  328,

      289,  336,  314,  329,  329,  336,  337,  305,  372,  374,
      337,  376,  401,  373,  372,  339,  372,  341,  418,  373,
      367,  373,  418,  419,  418,  431,  460,  419,  460,  419,
      448,  375,  448,  377,  401,  449,  448,  449,  484,  490,
      495,  449,  497,  188,  499,  500,  501,  431,  502,  165,
      498,  498,  498,  498,  460,  489,  472,  496,  496,  496,
      484,  490,  496,  495,  489,  497,  499,  500,  494,  493,
      501,  492,  502,   62,   62,   62,   62,   62,   65,   65,
       65,   65,   65,   68,   68,   68,   68,   68,   70,  491,
       70,   70,   70,  115,  115,  154,  154,  489,  154,  154,

      159,  159,  159,  159,  159,  162,  488,  162,  162,  162,
      487,  486,  485,  481,  480,  479,  483,  476,  475,  474,
      482,  481,  481,  480,  479,  480,  479,  480,  479,  476,
      475,  474,  474,  478,  477,  476,  475,  474,  473,  469,
      468,  467,  471,  464,  463,  462,  470,  469,  469,  468,
      467,  468,  467,  468,  467,  464,  463,  462,  462,  466,
      465,  464,  463,  462,  461,  459,  458,  457,  456,  455,
      454,  453,  452,  451,  450,  447,  446,  445,  444,  443,
      442,  441,  440,  439,  438,  437,  436,  435,  434,  433,
      432,  430,  429,  428,  427,  426,  425,  424,  423,  421,

      420,  417,  416,  415,  414,  413,  412,  411,  410,  409,
      408,  407,  406,  405,  404,  403,  402,  328,  391,  400,
      399,  386,  398,  397,  396,  395,  394,  393,  392,  366,
      391,  391,  390,  389,  388,  387,  386,  386,  385,  384,
      383,  382,  381,  380,  379,  378,  371,  370,  369,  368,
      366,  366,  366,  356,  365,  364,  350,  363,  362,  361,
      360,  359,  358,  357,  331,  356,  356,  354,  353,  352,
      351,  350,  350,  349,  348,  347,  346,  345,  344,  343,
      342,  335,  334,  333,  332,  331,  331,  331,  326,  325,
      324,  323,  320,  319,  318,  317,  316,  315,  313,  312,

      311,  310,  309,  308,  307,  306,  299,  298,  297,  296,
      295,  294,  293,  292,  291,  290,  285,  284,  283,  282,
      279,  278,  277,  276,  275,  274,  272,  271,  269,  268,
      267,  266,  265,  264,  257,  256,  255,  254,  253,  252,
      251,  250,  249,  248,  241,  241,  238,  237,  236,  235,
      234,  233,  216,  232,  229,  228,  226,  225,  224,  223,
      222,  221,  220,  219,  218,  217,  216,  216,  215,  212,
      211,  210,  207,  206,  202,  201,  200,  199,  198,  197,
      179,  196,  193,  192,  190,  189,  187,  186,  185,  184,
      183,  182,  181,  180,  179,  179,  178,  175,  174,  173,

      170,  169,  161,   69,   67,  153,  138,  150,  131,  149,
      148,  147,  114,   97,  111,   90,  110,  109,  108,  101,
       71,   69,   67,  503,   66,   66,    9,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503
    } ;

static yyconst flex_int16_t yy_chk[785] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,

        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    5,    6,   19,   19,   20,   20,
       20,   22,   24,   26,   23,  516,   39,   22,   25,   30,
       27,   23,  198,   29,   45,   32,   39,  515,   23,   28,
       19,  198,   23,   22,   24,   26,    5,    6,   23,   22,
       28,   25,   27,   30,   23,   29,   45,   32,   47,   42,
       23,   33,   28,   32,   23,   42,   48,   33,   46,   51,
       50,   44,   28,   33,   59,   30,   52,   33,   44,   49,
       47,   42,   72,   72,   59,   44,   75,   42,   48,   44,
       49,   46,   50,   51,   53,   44,   77,   66,   52,   66,

       53,   44,   49,  159,   52,  159,   53,   44,   75,  102,
       53,   44,   49,   64,  103,   51,  116,   71,   77,   64,
       64,   71,   71,   74,   74,   74,   80,   80,   84,   84,
      118,  102,  106,  106,  121,  121,  103,  141,  116,  125,
      125,  142,  145,  145,  164,   64,  156,  156,  164,  164,
      166,  167,  118,  168,  191,  180,  204,  181,   64,  141,
      217,  166,  203,  142,  168,  180,  205,  181,  227,  244,
      217,  239,  239,  203,  234,  218,  514,  205,  166,  167,
      181,  168,  191,  234,  204,  218,  252,  168,  191,  181,
      203,  252,  244,  253,  205,  254,  227,  287,  218,  243,

      205,  257,  227,  243,  243,  278,  257,  218,  294,  295,
      278,  296,  330,  294,  299,  253,  319,  254,  351,  299,
      287,  319,  353,  351,  364,  367,  401,  353,  431,  364,
      387,  295,  389,  296,  330,  387,  399,  389,  460,  472,
      484,  399,  490,  513,  495,  497,  499,  367,  500,  512,
      494,  493,  492,  491,  401,  489,  431,  488,  487,  486,
      460,  472,  485,  484,  483,  490,  495,  497,  482,  478,
      499,  477,  500,  504,  504,  504,  504,  504,  505,  505,
      505,  505,  505,  506,  506,  506,  506,  506,  507,  473,
      507,  507,  507,  508,  508,  509,  509,  471,  509,  509,

      510,  510,  510,  510,  510,  511,  470,  511,  511,  511,
      466,  465,  461,  459,  458,  457,  456,  455,  454,  453,
      452,  451,  450,  447,  446,  445,  444,  443,  442,  441,
      440,  439,  438,  437,  436,  435,  434,  433,  432,  430,
      429,  428,  427,  426,  425,  424,  423,  421,  420,  417,
      416,  415,  414,  413,  412,  411,  410,  409,  408,  407,
      406,  405,  404,  403,  402,  400,  398,  397,  396,  395,
      394,  393,  392,  390,  388,  385,  384,  383,  382,  381,
      380,  379,  378,  377,  376,  375,  374,  371,  370,  369,
      368,  365,  363,  362,  361,  360,  359,  358,  357,  354,

      352,  349,  348,  347,  346,  345,  344,  343,  342,  341,
      340,  339,  338,  335,  334,  333,  332,  329,  326,  325,
      324,  323,  322,  321,  320,  318,  317,  316,  315,  314,
      313,  312,  311,  310,  309,  308,  307,  306,  305,  304,
      303,  302,  301,  300,  298,  297,  293,  292,  291,  290,
      289,  288,  286,  285,  284,  283,  282,  281,  280,  279,
      277,  276,  275,  274,  273,  272,  271,  269,  268,  267,
      266,  265,  264,  263,  262,  261,  260,  259,  258,  256,
      255,  251,  250,  249,  248,  247,  246,  245,  238,  237,
      236,  235,  233,  232,  231,  230,  229,  228,  226,  225,

      224,  223,  222,  221,  220,  219,  215,  214,  213,  212,
      211,  210,  209,  208,  207,  206,  202,  201,  200,  199,
      197,  196,  195,  194,  193,  192,  190,  189,  187,  186,
      185,  184,  183,  182,  178,  177,  176,  175,  174,  173,
      172,  171,  170,  169,  163,  162,  153,  152,  151,  150,
      149,  148,  147,  146,  144,  143,  140,  139,  137,  136,
      135,  134,  133,  132,  130,  129,  128,  127,  126,  124,
      123,  122,  120,  119,  114,  113,  112,  111,  110,  109,
      108,  107,  105,  104,  100,   99,   96,   95,   94,   93,
       92,   91,   89,   88,   87,   86,   85,   83,   82,   81,

       79,   78,   70,   68,   67,   61,   60,   58,   57,   56,
       55,   54,   41,   40,   38,   37,   36,   35,   34,   31,
       15,   13,   11,    9,    8,    7,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "loadkeys.analyze.l"
#define YY_NO_INPUT 1
#line 5 "loadkeys.analyze.l"
#define YY_NO_INPUT 1

#include <stdlib.h>
#include <unistd.h> /* readlink */
#include <sys/param.h>
#include <linux/kd.h>
#include <linux/keyboard.h>

#include "ksyms.h"
#include "nls.h"
#include "kbd.h"
#include "paths.h"
#include "xmalloc.h"
#include "findfile.h"
#include "loadkeys.h"

int rvalct;
struct kbsentry kbs_buf;
static char *p, *pmax;

extern int verbose;
extern int yyerror(const char *s);
extern void lkfatal(const char *fmt, ...);

void stack_push(FILE *fd, int is_pipe, char *fname);

/* Include file handling - unfortunately flex-specific. */
#define MAX_INCLUDE_DEPTH 20
static struct infile {
	FILE *fd;
	char *filename;
	int  pipe;
	int  linenr;
	YY_BUFFER_STATE buffer;
} infile_stack[MAX_INCLUDE_DEPTH];

char *filename = NULL;
int  line_nr = 1;
static int  infile_stack_ptr = -1;

void stack_push(FILE *fd, int is_pipe, char *fname) {
	if (infile_stack_ptr >= MAX_INCLUDE_DEPTH)
		lkfatal(_("includes are nested too deeply"));

	infile_stack_ptr++;

	infile_stack[infile_stack_ptr].buffer   = yy_create_buffer(fd,YY_BUF_SIZE);
	infile_stack[infile_stack_ptr].fd       = fd;
	infile_stack[infile_stack_ptr].pipe     = is_pipe;
	infile_stack[infile_stack_ptr].filename = strdup(fname);
	infile_stack[infile_stack_ptr].linenr   = line_nr;

	yy_switch_to_buffer(infile_stack[infile_stack_ptr].buffer);

	// Set global variables
	filename = infile_stack[infile_stack_ptr].filename;
	line_nr  = 1;
}

static int stack_pop(void) {
	fpclose1(infile_stack[infile_stack_ptr].fd, infile_stack[infile_stack_ptr].pipe);

	// Free previous filename
	xfree(infile_stack[infile_stack_ptr].filename);

	// Destroy previous buffer
	yy_delete_buffer(infile_stack[infile_stack_ptr].buffer);

	infile_stack_ptr--;

	if (infile_stack_ptr >= 0) {
		// Set new state
		//yyin     = infile_stack[infile_stack_ptr].fd; // ???
		ispipe   = infile_stack[infile_stack_ptr].pipe;
		filename = infile_stack[infile_stack_ptr].filename;
		line_nr  = infile_stack[infile_stack_ptr].linenr;

		// Switch to new buffer
		yy_switch_to_buffer(infile_stack[infile_stack_ptr].buffer);
		return 0;
	}

	return 1;
}

/*
 * Where shall we look for an include file?
 * Current strategy (undocumented, may change):
 *
 * 1. Look for a user-specified LOADKEYS_INCLUDE_PATH
 * 2. Try . and ../include and ../../include
 * 3. Try D and D/../include and D/../../include
 *    where D is the directory from where we are loading the current file.
 * 4. Try KD/include and KD/#/include where KD = DATADIR/KEYMAPDIR.
 *
 * Expected layout:
 * KD has subdirectories amiga, atari, i386, mac, sun, include
 * KD/include contains architecture-independent stuff
 * like strings and iso-8859-x compose tables.
 * KD/i386 has subdirectories qwerty, ... and include;
 * this latter include dir contains stuff with keycode=...
 *
 * (Of course, if the present setup turns out to be reasonable,
 * then later also the other architectures will grow and get
 * subdirectories, and the hard-coded i386 below will go again.)
 *
 * People that dislike a dozen lookups for loadkeys
 * can easily do "loadkeys file_with_includes; dumpkeys > my_keymap"
 * and afterwards use only "loadkeys /fullpath/mykeymap", where no
 * lookups are required.
 */
static char *include_dirpath0[] = { "", 0 };
static char *include_dirpath1[] = { "", "../include/", "../../include/", 0 };
static char *include_dirpath2[] = { 0, 0, 0, 0 };
static char *include_dirpath3[] = {
	DATADIR "/" KEYMAPDIR "/include/",
	DATADIR "/" KEYMAPDIR "/i386/include/",
	DATADIR "/" KEYMAPDIR "/mac/include/", 0
};

static char *include_suffixes[] = { "", ".inc", 0 };

static FILE *find_incl_file_near_fn(char *s, char *fn)
{
	FILE *f = NULL;
	char *t, *te, *t1, *t2;
	int len;

	if (!fn)
		return NULL;

	t = xstrdup(fn);
	te = strrchr(t, '/');
	if (te) {
		te[1] = 0;
		len = strlen(t);
		include_dirpath2[0] = t;
		include_dirpath2[1] = t1 = xmalloc(len + 12);
		include_dirpath2[2] = t2 = xmalloc(len + 15);
		strcpy(t1, t);
		strcat(t1, "../include/");
		strcpy(t2, t);
		strcat(t2, "../../include/");
		f = findfile(s, include_dirpath2, include_suffixes);
		xfree(t1);
		xfree(t2);
	}
	xfree(t);
	return f;
}

static FILE *find_standard_incl_file(char *s)
{
	FILE *f;

	f = findfile(s, include_dirpath1, include_suffixes);
	if (!f)
		f = find_incl_file_near_fn(s, filename);

	/* If filename is a symlink, also look near its target. */
	if (!f) {
		char buf[MAXPATHLEN], path[MAXPATHLEN], *ptr;
		unsigned int n;

		n = readlink(filename, buf, sizeof(buf));
		if (n > 0 && n < sizeof(buf)) {
			buf[n] = 0;
			if (buf[0] == '/') {
				f = find_incl_file_near_fn(s, buf);

			} else if (strlen(filename) + n < sizeof(path)) {
				strcpy(path, filename);
				path[sizeof(path) - 1] = 0;
				ptr = strrchr(path, '/');
				if (ptr)
					ptr[1] = 0;
				strcat(path, buf);
				f = find_incl_file_near_fn(s, path);
			}
		}
	}

	if (!f)
		f = findfile(s, include_dirpath3, include_suffixes);
	return f;
}

static FILE *find_incl_file(char *s)
{
	FILE *f;
	char *ev;

	if (!s || !*s)
		return NULL;

	if (*s == '/')		/* no path required */
		return (findfile(s, include_dirpath0, include_suffixes));

	if ((ev = getenv("LOADKEYS_INCLUDE_PATH")) != NULL) {
		/* try user-specified path */
		char *user_dir[2] = { 0, 0 };
		while (ev) {
			char *t = strchr(ev, ':');
			char sv = 0;
			if (t) {
				sv = *t;
				*t = 0;
			}
			user_dir[0] = ev;
			if (*ev)
				f = findfile(s, user_dir, include_suffixes);
			else	/* empty string denotes system path */
				f = find_standard_incl_file(s);
			if (f)
				return f;
			if (t)
				*t++ = sv;
			ev = t;
		}
		return NULL;
	}
	return find_standard_incl_file(s);
}

static void open_include(char *s)
{
	FILE *fd;

	if (verbose)
		fprintf(stdout, _("switching to %s\n"), s);

	fd = find_incl_file(s);
	if (!fd)
		lkfatal(_("cannot open include file %s"), s);

	xfree(s);

	stack_push(fd, ispipe, pathname);
}




#line 1044 "loadkeys.analyze.c"

#define INITIAL 0
#define RVALUE 1
#define STR 2
#define INCLSTR 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 283 "loadkeys.analyze.l"


/* To protect from wrong code in the higher level parser (loadkeys.y), 
 * make sure we do not return a sensible value if we
 * do not intend to. (So wrong code would crash, or issue an error message.
 * I mean the code like the one for PLAIN handling in past loadkeys.y.
 * What to choose as the "bad" value: 0, -1?.. 
 * Well, make it equal to CODE_FOR_UNKNOWN_KSYM as the most efficient thing.
 */
#define YYLVAL_UNDEF CODE_FOR_UNKNOWN_KSYM
/* Every time yylex is called, initialize the associated
 * yylval to YYLVAL_UNDEF. Then it might be overwritten by specific rules. */
  yylval = YYLVAL_UNDEF;


#line 1243 "loadkeys.analyze.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 504 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 727 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 298 "loadkeys.analyze.l"
{
				BEGIN(INCLSTR);
			}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 301 "loadkeys.analyze.l"
{
				char *s = xstrndup(yytext+1, strlen(yytext)-2);
				/* use static pathname to store *s ? */
				open_include(s);
				BEGIN(0);
			}
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 307 "loadkeys.analyze.l"
{
				yyerror(_("expected filename between quotes"));
				BEGIN(0);
			}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(RVALUE):
case YY_STATE_EOF(STR):
case YY_STATE_EOF(INCLSTR):
#line 311 "loadkeys.analyze.l"
{
				stack_pop();
				if (!YY_CURRENT_BUFFER)
					yyterminate();
			}
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 316 "loadkeys.analyze.l"
{
				line_nr++;
			}
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 319 "loadkeys.analyze.l"
{
				line_nr++;
				BEGIN(0);
				return(EOL);
			}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 324 "loadkeys.analyze.l"
; /* do nothing */
	YY_BREAK
case 7:
/* rule 7 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 325 "loadkeys.analyze.l"
; /* do nothing */
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 326 "loadkeys.analyze.l"
{
				BEGIN(RVALUE);
				rvalct = 0;
				return(EQUALS);
			}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 331 "loadkeys.analyze.l"
{
				BEGIN(RVALUE);
				return(STRING);
			}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 335 "loadkeys.analyze.l"
{
				BEGIN(RVALUE);
				return(TO);
			}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 339 "loadkeys.analyze.l"
{
				yylval = strtol(yytext + 1, NULL, 16);
				if (yylval >= 0xf000)
					lkfatal(_("unicode keysym out of range: %s"), yytext);
				return(UNUMBER);
			}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 345 "loadkeys.analyze.l"
{
				yylval = strtol(yytext, NULL, 0);
				return(NUMBER);
			}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 349 "loadkeys.analyze.l"
{	return((yylval = ksymtocode(yytext, TO_AUTO)) == -1 ? ERROR : LITERAL);	}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 350 "loadkeys.analyze.l"
{	return(DASH);		}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 351 "loadkeys.analyze.l"
{	return(COMMA);		}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 352 "loadkeys.analyze.l"
{	return(PLUS);		}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 353 "loadkeys.analyze.l"
{	return(CHARSET);	}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 354 "loadkeys.analyze.l"
{	return(KEYMAPS);	}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 355 "loadkeys.analyze.l"
{	return(KEYCODE);	}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 356 "loadkeys.analyze.l"
{	return(PLAIN);		}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 357 "loadkeys.analyze.l"
{	return(SHIFT);		}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 358 "loadkeys.analyze.l"
{	return(CONTROL);	}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 359 "loadkeys.analyze.l"
{	return(ALT);		}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 360 "loadkeys.analyze.l"
{	return(ALTGR);		}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 361 "loadkeys.analyze.l"
{	return(SHIFTL);		}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 362 "loadkeys.analyze.l"
{	return(SHIFTR);		}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 363 "loadkeys.analyze.l"
{	return(CTRLL);		}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 364 "loadkeys.analyze.l"
{	return(CTRLR);		}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 365 "loadkeys.analyze.l"
{	return(CAPSSHIFT);	}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 366 "loadkeys.analyze.l"
{	return(ALT_IS_META);	}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 367 "loadkeys.analyze.l"
{	return(STRINGS);	}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 368 "loadkeys.analyze.l"
{	return(COMPOSE);	}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 369 "loadkeys.analyze.l"
{	return(AS);		}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 370 "loadkeys.analyze.l"
{	return(USUAL);		}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 371 "loadkeys.analyze.l"
{	return(ON);		}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 372 "loadkeys.analyze.l"
{	return(FOR);		}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 373 "loadkeys.analyze.l"
{
				yylval = strtol(yytext + 2, NULL, 8);
				return(CCHAR);
			}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 377 "loadkeys.analyze.l"
{
				yylval = (unsigned char) yytext[2];
				return(CCHAR);
			}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 381 "loadkeys.analyze.l"
{
				yylval = (unsigned char) yytext[1];
				return(CCHAR);
			}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 385 "loadkeys.analyze.l"
{
				p = (char *) kbs_buf.kb_string;
				pmax = p + sizeof(kbs_buf.kb_string) - 1;
				BEGIN(STR);
			}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 390 "loadkeys.analyze.l"
{
				if (p >= pmax)
					lkfatal(_("string too long"));
				*p++ = strtol(yytext + 1, NULL, 8);
			}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 395 "loadkeys.analyze.l"
{
				if (p >= pmax)
					lkfatal(_("string too long"));
				*p++ = '"';
			}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 400 "loadkeys.analyze.l"
{
				if (p >= pmax)
					lkfatal(_("string too long"));
				*p++ = '\\';
			}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 405 "loadkeys.analyze.l"
{
				if (p >= pmax)
					lkfatal(_("string too long"));
				*p++ = '\n';
			}
	YY_BREAK
case 45:
/* rule 45 can match eol */
YY_RULE_SETUP
#line 410 "loadkeys.analyze.l"
{
				char *ptmp = p;
				p += strlen(yytext);
				if (p > pmax)
					lkfatal(_("string too long"));
				strcpy(ptmp, yytext);
			}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 417 "loadkeys.analyze.l"
{
				*p = '\0';
				BEGIN(0);
				return(STRLITERAL);
			}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 422 "loadkeys.analyze.l"
{
				return(ERROR); /* report any unknown characters */
			}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 425 "loadkeys.analyze.l"
ECHO;
	YY_BREAK
#line 1660 "loadkeys.analyze.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 504 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 504 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 503);

	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#if defined(YY_NO_UNISTD_H) && !defined(__cplusplus)
extern int isatty (int );
#endif /* YY_NO_UNISTD_H && !__cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 425 "loadkeys.analyze.l"



