.TH SETLOGCONS 8 "24 October 2024" "kbd"

.SH NAME
setlogcons \- Send kernel messages to console N
.SH SYNOPSIS
.B setlogcons
[\fI\,options\/\fR]
[\fI\,N\/\fR]

.SH DESCRIPTION
The command
.B setlogcons
.I N
sets all kernel messages to the console specified as N.
.P
By default kernel messages are sent to the current console.
.P
To change the level of messages sent, use
.B dmesg

.SH OPTIONS
.TP
\fB\-C\fR, \fB\-\-console\fR=\fI\,DEV\/\fR
the console device to be used.
.TP
\fB\-V\fR, \fB\-\-version\fR
print version number.
.TP
\fB\-h\fR, \fB\-\-help\fR
print this usage message.

.SH AUTHORS
.B setlogcons
was originally written by Andries Brouwer for the kbd package.
.P
This manual page was written by Alastair McKinstry.
.SH "SEE ALSO"
.BR dmesg (1)
