.\" @(#)setvesablank.8
.TH SETVESABLANK 8 "14 Feb 2002" "kbd"
.SH NAME
setvesablank \- Turn VESA screen blanking on or off
.SH SYNOPSIS
.I setvesablank
[ [
.I -b --blanking
]
.I on | ON | off | OFF
] [
.I -h --help
]
[
.I -v --verbose
]
.LP
.SH DESCRIPTION
.IX "setvesablank command" "" "\fLsetvesablank\fR command"
.LP
The program
.B setvesablank
sets VESA screen blanking on or off.
.\" .SH AUTHOR
.\" Andries Brouwer <aeb@cwi.nl>.
.\" .br
.\" Man page by Alastair McKinstry <mckinstry@computer.org>
