.\" Copyright 2003 Alastair McKinstry <mckinstry@computer.org>"
.\" May be distributed under the GNU General Public License"
.TH VCSTIME 8 "22 Jan 2003" "kbd"

.SH NAME
vcstime \- Show time in upper right hand corner of the console screen

.SH SYNOPSIS
.B vcstime

.SH DESCRIPTION
.PP
.B vcstime
shows the current time in the upper right\-hand corner of the console screen.
.PP
This simple program shows the current time in the corner of the console screen.
.PP
It needs to be run by root, in order to have write permissions to
.I /dev/vcsa


.SH "AUTHORS"
.B vcstime
was written by Andries Brouwer, based on  a suggestion by Miguel de Icaza.
This manual page was Written by Alastair McKinstry, Debian, Jan 2003.
